import Head from 'next/head'
import Link from 'next/link'
import React, { Component } from 'react'

export default class index extends Component {
  render() {
    return (
      <React.Fragment>
        <Head>
          <title>Keep in touch</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container">
          <h1 className="text-3xl font-bold underline">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <Link href="/"> 
            <a>Start Page</a>
          </Link>
        </main>
      </React.Fragment>
    )
  }
}
